### ISSUE TITLE
Multiple dropdowns can be open at the same time

### ISSUE THREAD

**Issue by atollis** [dallaslu/bootstrap-5-multi-level-dropdown#5]
The "show" class is not being removed from other open dropdowns when a different one is clicked
![image](https://user-images.githubusercontent.com/4598812/119949942-b88f2a80-bfdd-11eb-95de-8dc1f370b1a7.png)

**Comment by atollis** [comment]
after investigation this is an conflict with the latest version of bootstrap 5.0.1, I do not get the same issue with 5.0.0-beta3 which is included in your fiddle

**Comment by dallaslu** [comment]
It is a mistake to hack for a version that has not yet been officially released. The Dropdown implementation logic has been modified for each version. I will try to solve this problem a little later. Hopefully this will be the last time.

**Comment by morrow95** [comment]
Here for the same reason.  Example being having three levels deep open.  If you click on first level to close it the next time you open it all three are open again.  The same behavior would happen with closing of second level.  Closing of any level should close all below it.

I noticed your comment above... https://getbootstrap.com/ shows BS sitting at 5.0.2 with no mention of alpha/beta so I imagine the current behavior should stick.

**Comment by morrow95** [comment]
I had some time to play around with this and the latest BS 5.0.2 version and get things working how I previously had them with BS4.  I modified the code to fit my needs, but maybe it will be useful to others.

A few changes of the changes I made : 

- Dropdown links can have an actual link rather than only #.  If a link other than # is in the html then it can be clicked to go to that link when the navbar is not collapsed, a touchscreen device is not being used, and hovering is enabled for that dropdown.  At the same time if a dropdown link with # is given and the navbar is not collapsed, a touchscreen device is not being used, and hovering is enabled for the dropdown it won't close the dropdown on click.  This is useful for main menu navbars with dropdowns.
- I commented out the clickEvent portion of the original code as it didn't do anything.
- Hovering is only enabled when the navbar is not collapsed.  When on smaller devices the dropdowns act normally with click only.
- Added two additional functions to check if navbar is collapsed or not and whether touch device is being used or not.

This code is specific to my use case of course, but might be useful to someone.  The main reason for my changes was to have dropdowns in my main menu at the top of the page, but at the same time make sure the usability is there on all screen sizes, devices, and with/without hovering.  If you plan on using this, at the minimum, you will need to adjust the selector for the isNav() function so it can properly detect if your main menu is collapsed or not (small screen or large screen detection).

```
(function($bs) {

	//class to check
    const CLASS_NAME = 'has-child-dropdown-show';
    
    $bs.Dropdown.prototype.toggle = function(_orginal) {
        return function() {
            document.querySelectorAll('.' + CLASS_NAME).forEach(function(e) {
                e.classList.remove(CLASS_NAME);
            });
            let dd = this._element.closest('.dropdown').parentNode.closest('.dropdown');
            for (; dd && dd !== document; dd = dd.parentNode.closest('.dropdown')) {
                dd.classList.add(CLASS_NAME);
            }
            return _orginal.call(this);
        }
    }($bs.Dropdown.prototype.toggle);
    
	document.querySelectorAll('.dropdown').forEach(function(dd) {
        dd.addEventListener('hide.bs.dropdown', function(e) {
	    		        		
            if(this.classList.contains(CLASS_NAME)) {
                this.classList.remove(CLASS_NAME);
                e.preventDefault();
            }
            
            //REMOVED from original code
            //if(e.clickEvent && e.clickEvent.composedPath().some(el=>el.classList && el.classList.contains('dropdown-toggle'))){
            //    e.preventDefault();
            //}
            
            e.stopPropagation(); // do not need pop in multi level mode
        });
    });

	//ADDED handle top level dropdown clicks (actual link or #)
    document.querySelectorAll('.dropdown [data-bs-toggle="dropdown"]').forEach(function(dd) {
		dd.addEventListener('click', function(e) {
					
        	//if full nav view AND not touch AND (one of the hovers is enabled)
        	if( isNav() && !isTouch() && (this.classList.contains('dropdown-hover') || Boolean(this.closest('.dropdown-hover-all')) ) ) {

				e.stopImmediatePropagation();

		    	//get href of clicked toggle
		    	var href = e.currentTarget.getAttribute('href');
		    	 			
	   			//goto link if not #
	   			if(href != '#') {
		    		location.href = href;
	   			}
	        }
        });
    });

    //ADDED isNav - is the desktop header shown or not
    function isNav() {
        return $('#header .navbar-toggler[data-bs-target="#navbar"]').is(':hidden'); //new way that doesn't use extra markup in pages or css
    }

    //ADDED isTouch - is this a touch device or not
    function isTouch() {
		return ('ontouchstart' in window || navigator.maxTouchPoints > 0 || navigator.msMaxTouchPoints > 0);
    }

	//for hover
    function getDropdown(element) {
    	//return $bs.Dropdown.getInstance(element) || new $bs.Dropdown(element);
        return $bs.Dropdown.getOrCreateInstance(element); //changed as it's the same thing
    }

	//dropdown-hover can be used on specific dropdown
	//dropdown-hover-all can be used on a container of elements
	//MODIFIED so hover only functions when nav is full view		
    document.querySelectorAll('.dropdown-hover.dropdown, .dropdown-hover-all .dropdown').forEach(function(dd) {
        dd.addEventListener('mouseenter', function(e) {
            let toggle = e.target.querySelector(':scope>[data-bs-toggle="dropdown"]');
            if( !toggle.classList.contains('show') && isNav() ) {
                getDropdown(toggle).toggle();
            }
        });
        dd.addEventListener('mouseleave', function(e) {
            let toggle = e.target.querySelector(':scope>[data-bs-toggle="dropdown"]');
            if( toggle.classList.contains('show') && isNav() ) {
                getDropdown(toggle).toggle();
            }
        });
    });
})(bootstrap);
```
